# iq baseline
python train_iq.py env=mujoco_ant-v2 agent=sac agent.actor_lr=3e-05 agent.critic_lr=0.0003 expert.demos=25 train.eval_interval=1000 seed=0 log_interval=100 exp_name=seed_0_actorlr_3e-5_criticlr_3e-4_roulen_1_trainstps_1


# Lift IIWA
# better 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_IQ
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_confexpert_angle_60

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_30_confexpert_angle_90_filter


# worse 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_IQ
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_confexpert_angle_60

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_30_confexpert_angle_90_filter



# better_worse 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_IQ
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_confexpert_angle_60

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_30_confexpert_angle_90_filter


# better_failed 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_IQ
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_confexpert_angle_60

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_failed_30_confexpert_angle_90_filter




# worse_failed 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_IQ
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_confexpert_angle_60

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_worse_failed_30_confexpert_angle_90_filter



# better_worse_failed 30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_IQ

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_confexpert_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_maxlamb_angle_90


python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_30.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=30 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_30_confexpert_angle_90_filter




# better_worse_failed 60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_IQ

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_confexpert_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_confexpert_angle_90

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_maxlamb_angle_90


python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_60.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=60 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_60_confexpert_angle_90_filter



# better_worse_failed 90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.conf_learn=IQ device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_IQ

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=120 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_120
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=150 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_150
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=180 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_180


python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_30
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_60
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_90
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=120 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_120
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=150 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_150
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=180 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_180


python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=30 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_30_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=60 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_60_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=90 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_90_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=120 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_120_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=150 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_150_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=180 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_180_filter



python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=5 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_5
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=10 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_10
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=15 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_15
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=20 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_20
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=25 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_25

python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=5 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_5
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=10 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_10
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=15 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_15
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=20 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_20
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=25 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=0.7 C_aware.conf_learn=max_lamb device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_maxlamb_angle_25


python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=5 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_5_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=10 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_10_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=15 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_15_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=20 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_20_filter
python train_iq_dyrank.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_better_worse_failed_90.pkl agent=sac agent.actor_lr=5e-06 agent.critic_lr=5e-06 agent.init_temp=0.001 expert.demos=90 expert.subopt_class_num=1 env.ignore_done=True env.horizon=200 eval.horizon=200 seed=1 train.boundary_angle=25 train.roullout_length=1 train.train_steps=1 train.eval_interval=1000 log_interval=100 C_aware.lamb=1 C_aware.conf_learn=conf_expert device=cpu exp_name=seed_1_actorlr_5e-6_criticlr_5e-6_roulen_1_trainstps_1_better_worse_failed_90_confexpert_angle_25_filter



# render
# max_lamb
python test_iq.py eval.eps=100 env=robosuite_Lift_IIWA env.horizon=200 agent=sac env.has_renderer=True eval.policy=/root/Docker_RoboLearn/Outputs/outputs/better_worse_failed_90_angle/maxlamb_angle_30/results/431000_returns_94.217_succeed_0.9
# IQ
python test_iq.py eval.eps=100 env=robosuite_Lift_IIWA env.horizon=200 agent=sac env.has_renderer=True eval.policy=/root/Docker_RoboLearn/Outputs/outputs/better_worse_failed_60/IQ/results/133000_returns_48.334_succeed_0.4
# confexpert
python test_iq.py eval.eps=100 env=robosuite_Lift_IIWA env.horizon=200 agent=sac env.has_renderer=True eval.policy=/root/Docker_RoboLearn/Outputs/outputs/better_worse_failed_60/confexpert_angle_60/results/188000_returns_63.459_succeed_0.8
# 60 filter
python test_iq.py eval.eps=100 env=robosuite_Lift_IIWA env.horizon=200 agent=sac env.has_renderer=True eval.policy=/root/Docker_RoboLearn/Outputs/outputs/better_worse_failed_60/angle_60_filter/results/295000_returns_57.004_succeed_0.8

# 好模型
python test_iq_dyrank.py eval.eps=100 env=robosuite_Lift_IIWA env.horizon=500 agent=sac env.has_renderer=False eval.policy=/root/RoboLearn/Confidence-Aware-IQ-Learn/iq_learn/outputs/better_failed_30/11-46-58/results/496000_returns_25.384_succeed_0.5


# irl reward
python test_iq_reward.py env=robosuite_Lift_IIWA env.demo=Suboptimal/Lift/robosuite_Lift_IIWA_50.pkl expert.demos=50 env.horizon=500 agent=sac env.has_renderer=False eval.policy=/root/RoboLearn/Confidence-Aware-IQ-Learn/iq_learn/outputs/2023-09-19/22-42-45/results/333000_returns_57.524_succeed_0.8






