#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tcp-socket','console_scripts','ee_topic_sub'
__requires__ = 'tcp-socket'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tcp-socket', 'console_scripts', 'ee_topic_sub')()
    )
